// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import RichText from './RichText';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	RichText,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	rich_text: RichText,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
